### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by hexiangquan** [jasonlo0509/Font2Font#1]
Handwritten Chinese Font Generation with Collaborative Stroke Refinement？  do you have any plan to code this paper's model?

**Comment by yunchenlo** [comment]
Hi, 
    Currently there is no plan to code the model. We are too busy.
    But we do provide bold data augmentation function in src/zi2zi/model/dataset.py. Intuitively bold can solve the stroke issue. You can run that and test if it is better.

yclo

**Comment by hexiangquan** [comment]
i have rewrite  code  ,but  train set  perfermance very good  .but  in test mode ,bad  your bold code  is difference with  paper's discription

**Comment by yunchenlo** [comment]
Yes, we are not 100% implementing the paper's method.
You need to train a model which can bold the word in the original paper. Here we just enlarge the photo to mimic the bold effect.
